name: MGTrapdoorSpleef
main: com.comze_instancelabs.trapdoorspleef.Main
version: 1.0.1
author: InstanceLabs
softdepend: [Vault, MinigamesAPI]
depend: [MinigamesAPI]
loadbefore: [MinigamesAPI]
commands:
   tds:
      description: Main command
      usage: /wl [action]
      aliases: [trapdoorspleef, mgtrapdoorspleef]
