name: MGTrapdoorSpleef
main: com.comze_instancelabs.trapdoorspleef.Main
version: ${minigames.releaseversion}-${minigames.timestamp}
author: InstanceLabs
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   tds:
      description: Main command
      usage: /wl [action]
      aliases: [trapdoorspleef, mgtrapdoorspleef]
